---
- name: Set up Kubernetes Cluster
  hosts: k8s_cluster
  become: true
  tasks:

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Disable swap (required for Kubernetes)
      command: swapoff -a
      when: ansible_os_family == "Debian"

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      when: inventory_hostname == "master"
      register: k8s_init
      ignore_errors: true

    - name: Copy Kubernetes admin config to user home
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - chown $(id -u):$(id -g) $HOME/.kube/config
      when: inventory_hostname == "master"

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel.yml
      when: inventory_hostname == "master"

    - name: Join worker nodes to the cluster
      command: "{{ hostvars['master']['k8s_init']['stdout_lines'][-1] }}"
      when: inventory_hostname != "master"
