---
- name: Notification Automation Playbook
  hosts: localhost
  tasks:

    # Task 1: Send Email via Gmail SMTP
    - name: Send Email Notification
      mail:
        host: smtp.gmail.com
        port: 587
        username: 'your_email@gmail.com'
        password: 'your_app_password'
        to: 'recipient_email@gmail.com'
        subject: "Ansible Email Notification"
        body: "This is an automated email notification sent using Ansible."
        secure: starttls

    # Task 2: Send WhatsApp Message via Twilio
    - name: Send WhatsApp Notification
      command: >
        curl -X POST https://api.twilio.com/2010-04-01/Accounts/{{ TWILIO_ACCOUNT_SID }}/Messages.json
        --data-urlencode "Body=This is an automated WhatsApp message sent using Ansible."
        --data-urlencode "From=whatsapp:+14155238886"
        --data-urlencode "To=whatsapp:+your_phone_number"
        -u {{ TWILIO_ACCOUNT_SID }}:{{ TWILIO_AUTH_TOKEN }}

    # Task 3: Send SMS Message via Twilio
    - name: Send SMS Notification
      command: >
        curl -X POST https://api.twilio.com/2010-04-01/Accounts/{{ TWILIO_ACCOUNT_SID }}/Messages.json
        --data-urlencode "Body=This is an automated SMS message sent using Ansible."
        --data-urlencode "From=+your_twilio_phone_number"
        --data-urlencode "To=+your_phone_number"
        -u {{ TWILIO_ACCOUNT_SID }}:{{ TWILIO_AUTH_TOKEN }}
