- hosts: all
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Ensure all packages are up to date
      yum:
        name: '*'
        state: latest
