- hosts: all
  tasks:
    - name: Ensure user exists
      user:
        name: john_doe
        state: present
        shell: /bin/bash
        groups: wheel
        password: "{{ 'mypassword' | password_hash('sha512') }}"

    - name: Ensure user is removed
      user:
        name: temp_user
        state: absent
