- hosts: all
  tasks:
    - name: Set permissions on a directory
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'
        state: directory

    - name: Set permissions on a file
      file:
        path: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
